# Generated by Django 6.0.4 on 2026-04-25 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userprofile_options_userprofile_account_locked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
